apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-kubernetes-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-kubernetes-project
  template:
    metadata:
      labels:
        app: kafka-kubernetes-project
    spec:
      containers:
        - name: kafka-kubernetes-project-container
          image: kafka-kubernetes-project-image:latest
          command: ["java", "-jar", "my-app.jar"]
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092