apiVersion: v1
kind: Service
metadata:
  name: kafka-kubernetes-project-service
spec:
  selector:
    app: kafka-kubernetes-project
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer